### ISSUE TITLE
Touch input not working in SliverPinnedHeader

### ISSUE THREAD

**Issue by awanishraj** [Kavantix/sliver_tools#12]
Touch inputs are working initially, but when the header is pinned to the leading-edge, touch inputs are ignored.

**Comment by awanishraj** [comment]
Add these lines in RenderSliverPinnedHeader class

```dart
  @override
  double childMainAxisPosition(RenderBox child) {
    assert(child == this.child);
    return 0;
  }

  @override
  bool hitTestChildren(
    SliverHitTestResult result, {
    @required double mainAxisPosition,
    @required double crossAxisPosition,
  }) {
    assert(geometry.hitTestExtent > 0.0);

    return child != null &&
        hitTestBoxChild(
          BoxHitTestResult.wrap(result),
          child,
          mainAxisPosition: mainAxisPosition,
          crossAxisPosition: crossAxisPosition,
        );
  }
```

**Comment by Kavantix** [comment]
Thanks for submitting the issue!
The problem turned out to be that `RenderSliverSingleBoxAdapter` by default sets its childMainAxisPosition to the scrollOffset which is not what is needed here
(So the hitTestChildren part is already correctly supplied by the parent)
