### ISSUE TITLE
Hittest does not work for SliverPositioned in combination with sliverstack

### ISSUE THREAD

**Issue by remonh87** [Kavantix/sliver_tools#15]
I create the following unit test with a working scenario and a failing one: https://gist.github.com/remonh87/bd6d8583e70955b23f2fdccfb390a9b3

When I try to app on a child of the SliverPositioned it does not react on the ontap. I did some debug printing and noticed that the hittest is not by the positioned in my example and will be passed through to the slivertoboxadapter.

Expected behaviour: onTap to be executed

**Comment by Kavantix** [comment]
Thanks for submitting!
Should be fixed in 0.1.7

**Comment by remonh87** [comment]
Thank you for the quick fix will test it today!
