### ISSUE TITLE
Where to find resources about building custom slivers

### ISSUE THREAD

**Issue by wuweijian1997** [Kavantix/sliver_tools#19]
Are there any article or tutorials?..

**Comment by Kavantix** [comment]
What exactly do you want to learn/read about?

**Comment by wuweijian1997** [comment]
> What exactly do you want to learn/read about?

...
Custom sliver widget like you sliver_tools.

**Comment by Kavantix** [comment]
You want to learn how to build your own custom sliver widget?
Then take a look at [slivers demystified](https://medium.com/flutter/slivers-demystified-6ff68ab0296f). And you can also look at the code of already existing slivers like in flutter itself and my package to try understand how they work.

**Comment by wuweijian1997** [comment]
Thank you.
