### ISSUE TITLE
Add SliverStack

### ISSUE THREAD

**Issue by Kavantix** [Kavantix/sliver_tools#2]
A widget that stacks its children just like the Stack widget.

Must have:
- [x] list of children
- [x] size depends on children

Nice to have:
- [ ] alignment of children
- [x] using positioned children

**Comment by felixjaehn** [comment]
Wanted to ask a quick question to the SliverStack. How do I position a Positioned Element at the bottom of the Stack. Because when I am using bottom: 0 in the SliverPositioned the item that should be positioned at the bottom stays at the top.
