### ISSUE TITLE
SliverVisibilityDetector

### ISSUE THREAD

**Issue by volser** [Kavantix/sliver_tools#21]
like this one https://pub.dev/packages/visibility_detector (or this https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)
but for sliver (with better performance and without delay if possible)

use case: highlight some links/buttons/sections if SliverList is in viewport while scrolling

**Comment by Kavantix** [comment]
This is probably out of scope for this library.
Perhaps you could try using `SliverLayoutBuilder` for this purpose?

**Comment by Kavantix** [comment]
I’m closing this issue as I feel it is out of scope, if you disagree feel tree to comment and I’ll reopen it
