### ISSUE TITLE
Migration to Null Safety

### ISSUE THREAD

**Issue by EdsonBueno** [Kavantix/sliver_tools#23]
With Null Safety increasing in popularity, it would be great to have this package migrated.

**Comment by Kavantix** [comment]
I've done the migration but haven't tested it yet.
If you want you can take a look at the `nullsafety` branch I pushed the migrated code there.
I don't expect any issues with it, since the migration was fairly straightforward (and even fixed 2 very tiny edgecases)

**Comment by venkatd** [comment]
@Kavantix 

It's possible that a few parts were missed. I tried running with the following in my pubspec.yaml:

```yaml
  sliver_tools:
    git:
      url: https://github.com/Kavantix/sliver_tools.git
      ref: nullsafety
```

One error I get for example is:
../../../flutter/.pub-cache/git/sliver_tools-c3529eb47c69d893ddcb270ca993d9861a17cb1c/lib/src/sliver_stack.dart:516:9: Error: Non-nullable variable 'minPaintOrigin' must be assigned before it can be used.

This is because there are some lines of non-nullable variables that aren't initialized
https://github.com/Kavantix/sliver_tools/blob/nullsafety/lib/src/sliver_stack.dart#L505

We have something like `double minPaintOrigin` which should be initialized to 0 or declared right where it's value is set. I think if we moved that declaration to where it's set, that would resolve the error.

Pasting all the errors I see below:
```
Running "flutter pub get" in turtle_app...
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at
https://flutter.dev/go/android-project-migration
to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Launching lib/main.dart on macOS in debug mode...
 lib/main.dart
../../../flutter/.pub-cache/git/sliver_tools-c3529eb47c69d893ddcb270ca993d9861a17cb1c/lib/src/multi_sliver.dart:308:20: Warning: Operand of null-aware operation '??' has type 'double' which excludes null.
      paintOrigin: minPaintOrigin ?? 0,
                   ^
../../../flutter/.pub-cache/git/sliver_tools-c3529eb47c69d893ddcb270ca993d9861a17cb1c/lib/src/sliver_stack.dart:516:9: Error: Non-nullable variable 'minPaintOrigin' must be assigned before it can be used.

        minPaintOrigin ?? double.infinity,
        ^^^^^^^^^^^^^^
../../../flutter/.pub-cache/git/sliver_tools-c3529eb47c69d893ddcb270ca993d9861a17cb1c/lib/src/sliver_stack.dart:516:9: Warning: Operand of null-aware operation '??' has type 'double' which excludes null.
        minPaintOrigin ?? double.infinity,
        ^
../../../flutter/.pub-cache/git/sliver_tools-c3529eb47c69d893ddcb270ca993d9861a17cb1c/lib/src/sliver_stack.dart:535:20: Error: Non-nullable variable 'minPaintOrigin' must be assigned before it can be used.
      paintOrigin: minPaintOrigin ?? 0,
                   ^^^^^^^^^^^^^^
../../../flutter/.pub-cache/git/sliver_tools-c3529eb47c69d893ddcb270ca993d9861a17cb1c/lib/src/sliver_stack.dart:535:20: Warning: Operand of null-aware operation '??' has type 'double' which excludes null.
      paintOrigin: minPaintOrigin ?? 0,
                   ^

Command PhaseScriptExecution failed with a nonzero exit code

note: Using new build system
note: Planning build
note: Constructing build description
** BUILD FAILED **
Exception: Build process failed
Exited (sigterm)
```

**Comment by Kavantix** [comment]
Thanks for testing @venkatd, it seems I incorrectly put a `!` hint for the migration tool and it did not complain that it would not work.
`minPaintOrigin` should actually be nullable there.

I've updated the branch, would be really appreciated if you could test it again 😃

**Comment by venkatd** [comment]
Hi @Kavantix here is what I get with SliverStack during running of my app:

```

LateInitializationError: Field 'paintOffset' has not been initialized.

The relevant error-causing widget was
SliverStack
lib/task_manager/task_manager.dart:665
When the exception was thrown, this was the stack
#0      SliverStackParentData.paintOffset (package:sliver_tools/src/sliver_stack.dart)
package:sliver_tools/src/sliver_stack.dart:1
#1      SliverStackParentData.simpleStackParentData
package:sliver_tools/src/sliver_stack.dart:410
#2      RenderSliverStack.performLayout
package:sliver_tools/src/sliver_stack.dart:588
#3      RenderObject.layout
package:flutter/…/rendering/object.dart:1784
#4      RenderViewportBase.layoutChildSequence
package:flutter/…/rendering/viewport.dart:512
...
```

Seems like a timing issue where paintOffset is used before it soon gets initialized.

This is related to the
```
late Offset paintOffset;
```

When does paintOffset get initialized and where is it used? Some ideas:
- If it doesn't break the code could declare as `Offset paintOffset = Offset.zero`
- Rewrite as a nullable var like `Offset? paintOffset` and handle the nulls

I don't understand the code well enough to make the right call :)

**Comment by Kavantix** [comment]
Yeah null was fine before indeed, but zero is the nicer option using nnbd.
Should be fixed now.

Thanks again for testing!, let me know if you find anything else :)

**Comment by venkatd** [comment]
All working for me now! And thank YOU for the SliverStack widget, it has been very helpful for implementing our task manager feature.

We are only using SliverStack so I can't confirm if the other widgets have any issues. Will let you know if I run into any issues with SliverStack.

**Comment by Kavantix** [comment]
I published a preview version to pub `0.2.0-nullsafety`, since all tests pass it should work as expected

**Comment by EdsonBueno** [comment]
I tested it and everything looks fine @Kavantix 
Thank you

**Comment by EdsonBueno** [comment]
Now that null safety is stable in Dart, you can release the null safety migration as a stable release (instead of a pre-release) so that the package earns the "Null Safety" badge on pub.dev.
https://dart.dev/null-safety/migration-guide#step5-publish

**Comment by Kavantix** [comment]
I was just working on some more 'breaking-ish' changes that I wanted to include since I was updating to a new major version anyways.
0.2.0 is now released, enjoy!
And thanks for testing @EdsonBueno @venkatd!
