### ISSUE TITLE
SliverGeometry has a paintOffset that exceeds the remainingPaintExtent from the constraints.

### ISSUE THREAD

**Issue by marcos930807** [Kavantix/sliver_tools#28]
After upgrade to version 0.2.0, this error Came.(version 0.1.10 Works Great)

This is small repo to reproduce the error.
https://github.com/marcos930807/sliver_demo.
After open de app just Expand "Batidos/Milkshakes" and see console logs.

The Complete Error:
SliverGeometry has a paintOffset that exceeds the remainingPaintExtent from the constraints.
The render object whose geometry violates the constraints is the following: RenderMultiSliver#2d301 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
The remainingPaintExtent is 555.4666669999999, but the paintOrigin + paintExtent is 555.466667.

Maybe you have fallen prey to floating point rounding errors, and should explicitly apply the min() or max() functions, or the clamp() method, to the paintOrigin + paintExtent?

The paintOrigin and paintExtent must cause the child sliver to paint within the viewport, and so cannot exceed the remainingPaintExtent.

**Comment by Kavantix** [comment]
Hey @marcos930807 thanks for filing this with a repro!
It seems my attempt to mute this annoying error has actually triggered it for you.
I’ll be sure to take a look at it.

But in the meantime it’s probably good to know that you can basically ignore this error, as you can see the difference is only a floating point precision issue not an actual error.
But still this should not happen as it is very annoying

PS. Any chance you’d be able to rewrite the repro into a widgetTest so I could include it and thus prevent it from ever returning?

**Comment by Kavantix** [comment]
@marcos930807 Could you test using the version of #29

**Comment by marcos930807** [comment]
@Kavantix, Sorry the delay was busy, I'm going to test and let you know.

**Comment by Kavantix** [comment]
> @Kavantix, Sorry the delay was busy, I'm going to test and let you know.

No worries we're all busy :) thanks!

**Comment by marcos930807** [comment]
Hi @Kavantix the fix work great.
I updated the demo https://github.com/marcos930807/sliver_demo  using the reference #29 as a dependency and the problem go away.
Thanks!!
