### ISSUE TITLE
SliverGeometry is not valid: The "maxPaintExtent" is less than the "paintExtent". with MultiSliver usage

### ISSUE THREAD

**Issue by TatsuUkraine** [Kavantix/sliver_tools#30]
Usage MultiSliver with SliverAppBar leads to exception `SliverGeometry is not valid: The "maxPaintExtent" is less than the "paintExtent".`

```dart
Scaffold(
    body: CustomScrollView(
      slivers: [
        const SliverAppBar(
          pinned: true,
          title: Text('Sample'),
        ),
        MultiSliver(
          children: [
            SliverToBoxAdapter(
              child: Container(
                height: 30, ///<--- changing this value to height bigger than app bar fixes issue
              ),
            ),
          ]
        ),
        MultiSliver(
            children: [
              SliverList(
                delegate: SliverChildBuilderDelegate(
                  (context, index) {
                    return Container(
                      height: 50,
                      width: double.infinity,
                      color: index.isEven ? Colors.red : Colors.blue,
                    );
                  },
                  childCount: 20,
                ),
              ),
              const SliverToBoxAdapter(
                child: Divider(),
              ),
            ]
        ),
      ],
    ),
  );
```

Flutter version: 2.0.5
Device: Android 11 (API 30) (emulator)

**Comment by Kavantix** [comment]
Hey @TatsuUkraine thanks for filing this.
Seems like an interesting bug indeed, I'll look into it ASAP

Does this affect how it renders or only show the error in the console?

**Comment by TatsuUkraine** [comment]
Hey. Thank you for quick response) yes it affects. Second MultiSliver just stops moving

**Comment by TatsuUkraine** [comment]
In more complex example , where I noticed this issue, it looks to me that other content is actually moving during the scroll, except multi sliver that goes just after a small one, but I could be wrong, didn't pay attention a lot) last hour was trying to reproduce this issue with very primitive example that I've sent you))

**Comment by Kavantix** [comment]
Could you test using PR #31

**Comment by TatsuUkraine** [comment]
it seems it fixes the issue

**Comment by Kavantix** [comment]
Just published the fix as 0.2.2

**Comment by TatsuUkraine** [comment]
thank you for fast reaction)

**Comment by felixjaehn** [comment]
I faced the same Issue again today on the latest version (0.2.4)

https://user-images.githubusercontent.com/31625592/121203605-86e85000-c876-11eb-9283-94907cdfe4ca.mp4

As this weird behaviour is occuring I get the same error message.
"SliverGeometry is not valid: The "maxPaintExtent" is less than the "paintExtent"."

```
MultiSliver(
          children: <Widget>[
            SliverPersistentHeader(
              pinned: true,
              delegate: SliverHeader(
                title: title,
                index: index,
              ),
            ),
            SliverToBoxAdapter(child: formView),
            SliverPersistentHeader(
              pinned: true,
              delegate: SubtitleHeader(
                subtitle: subtitle,
                index: index,
              ),
            ),
          ],
        )
```

Flutter version: 2.2.1
This error doesn't occur in release mode

**Comment by Kavantix** [comment]
@felixjaehn please open a new issue and include a minimal runnable code sample that reproduces the problem
