### ISSUE TITLE
How to use SliverAnimatedPaintExtent and animated the Scroll position at the same time?

### ISSUE THREAD

**Issue by basketball-ico** [Kavantix/sliver_tools#32]
For example, in a list that has a button to load more, show progress, and then show an error message with retry button, the loading widget is changed to the one with the error message, I would like to scroll to the end to show the complete error message.

without `SliverAnimatedPaintExtent` I can do this
```dart
await scrollControllerAnimateTo(
  scrollController.position.maxScrollExtent,
  duration: Duration(milliseconds: 300),
  curve: Curves.easeOut,
);
```

but if I use the `SliverAnimatedPaintExtent` it only animates a little bit, since the` maxScrollExtent` is growing while the `SliverAnimatedPaintExtent` animation is running.

Is there any way to synchronize the `AnimateTo` of the` scrollController` with that of the `SliverAnimatedPaintExtent`.

a temporary solution for me would be to wait for the milliconds of the animation of `SliverAnimatedPaintExtent` and then do the` jumpTo`, but that delay is uncomfortable.

```dart
await Future <void> .delayed (paintExtentDuration);
await scrollControllerAnimateTo (
   scrollController.position.maxScrollExtent,
   duration: Duration (milliseconds: 300),
   curve: Curves.easeOut,
);
```
the idea is that they are animated in time, or with the least possible delay.

If you have a suggestion, I would appreciate it very much

**Comment by Kavantix** [comment]
That’s definitely an interesting question.
I don’t really have a solution for how to get your current approach working at the moment.
But how about changing it a little
For instance instead of showing the error message within the animatedpaintextent put it outside, that way you can scroll to the end immediately.

**Comment by Kavantix** [comment]
I'm closing this in the assumption my answer solved your problem, if you have further questions or disagree feel free to comment and I'll reopen this issue.
