### ISSUE TITLE
SliverIndexedStack

### ISSUE THREAD

**Issue by shashkiranr** [Kavantix/sliver_tools#36]
Hi Pieter,

Thank you for an amazing plugin. Is it possible to add SliverIndexedStack that works like an IndexedStack but accepts Slivers.

Best,
Shashi

**Comment by Kavantix** [comment]
Hi @shashkiranr,

Thanks for the compliment and the suggestion!

Adding this widget should not be too difficult but I'm not sure when I'll have time to get to it.
Would you be open to making a PR?

**Comment by Kavantix** [comment]
@shashkiranr could you test the widget I introduce in #39

**Comment by Kavantix** [comment]
Decided this will not be part of the package since I don't see a usecase.
If anyone does see a usecase feel free to comment and I'll gladly discuss and/or reopen
