### ISSUE TITLE
[DOC] Please Add More example

### ISSUE THREAD

**Issue by l-7-l** [Kavantix/sliver_tools#37]
Thank you for your great work, please add more ***gif*** and ***code*** ***examples***, maybe I am too stupid, I don’t know what I can do with it

**Comment by Kavantix** [comment]
@G11Max Do you have an example of something extra you would expect?

Or alternatively, what brought you to the package? Perhaps I can assist in determining if you can use it.

**Comment by l-7-l** [comment]
@Kavantix  ohhhhhhhhhhhhhhh sorry for the late reply. 

I want to achieve the effect of sliding up the feed container of the  [profile page in this link](https://dribbble.com/shots/14179883-Instagram-Redesign-Part-3). It looks like a stack, but I have no idea. 

**Before Sliding up/scroll**
![b](https://user-images.githubusercontent.com/20581031/139901396-7c95cf37-8abb-4ac9-aa4a-f9d9933b1171.png)

**When Sliding up/scrolling**

![d](https://user-images.githubusercontent.com/20581031/139905592-1e97f40f-15aa-4c68-9027-43b51f40dd0b.png)

The profile Container is Fixed, like a fixed stack. 

please forgive my poor english

**Comment by Kavantix** [comment]
@G11Max I guess you figured it out since you closed the issue?

**Comment by l-7-l** [comment]
@Kavantix not yet....
