### ISSUE TITLE
SliverAnimatedSwitcher not working

### ISSUE THREAD

**Issue by HeavyMedaI** [Kavantix/sliver_tools#40]
Hello, i couldnt run SliverAnimatedSwitcher, can you provide an example usage on Readme so we can understand.

**Comment by Kavantix** [comment]
Hi @musaatalay1, `SliverAnimatedSwitcher` works the same as the normal `AnimatedSliver` so just give it a child and then change the child to trigger the animation

**Comment by Kavantix** [comment]
I’m gonna assume you managed to get it working.
Otherwise just comment here and I’ll gladly reopen and help
