### ISSUE TITLE
MultiSliver has unexpected behavior when use centerKey in CustomScrollView

### ISSUE THREAD

**Issue by MiniSuperDev** [Kavantix/sliver_tools#49]
Hi, I try to create a bidirectional lazy load list like the like flutter docs said 
https://github.com/flutter/flutter/blob/5464c5bac742001448fe4fc0597be939379f88ea/packages/flutter/lib/src/widgets/scroll_view.dart#L502-L513

I create a [gist](https://gist.github.com/MiniSuperDev/23cf9e1809ca9dc29d38ecf00a167f06) where you can enable a disable the `MultiSliver`, and you can see that the scroll behavior is different, is looks like a stack, and also list is iterate in different order.

On the other hand, maybe do you know other way to create a list that append items to the top of the list by preserving the scroll, the solution that I used is from https://github.com/flutter/flutter/issues/21541#issuecomment-629121578 

I used `MultiSliver` because my list is grouped and has pinned headers for each group, like [this](https://stackoverflow.com/a/64518151).

thank you

**Comment by Kavantix** [comment]
Hi @MiniSuperDev, thanks for reporting this! Could you try making a failing widget test from your example, that would help a lot since I’m a bit swamped atm.

**Comment by MiniSuperDev** [comment]
hello @Kavantix, thanks, unfortunately I don't know how to do the test widgets at the moment, I still need to learn that, so I couldn't for now, sorry :)

**Comment by Kavantix** [comment]
@MiniSuperDev thanks again for pointing out the issue and providing the gist.
I fixed it in PR #51 , could you also test it

**Comment by MiniSuperDev** [comment]
@Kavantix hello, I already tried it and it works as expected, good job, thanks.
