### ISSUE TITLE
Obsolete example

### ISSUE THREAD

**Issue by jpolstre** [Kavantix/sliver_tools#52]
Thanks for the plugin, but I could update it, it's been a long time without updating. Thank you.

**Comment by Kavantix** [comment]
@jpolstre could be a little more specific?

**Comment by globalwebforce** [comment]
@Kavantix we think you should show an updated full code of the the GIF demo you showed on pub.dev + a working flutter project showcasing all the package features, just like the other flutter packages on pub.dev.

**Comment by Kavantix** [comment]
@globalwebforce The example code of the GIF should still work.
Any extra examples showing off features are welcome as PR's but it is not something I have time for at the moment.

@jpolstre is that also what you meant?

**Comment by Kavantix** [comment]
Updated the example to flutter 3.3
