### ISSUE TITLE
Is there a way to stop/ignore scroll gestures on pinned SliverPinnedHeader?

### ISSUE THREAD

**Issue by rupinderjeet** [Kavantix/sliver_tools#53]
When `SliverPinnedHeader` is `pinned`, is there a way to prevent any scroll gestures on it? As of now, scroll gestures cause the `CustomScrollView` to scroll.

**Comment by Kavantix** [comment]
I haven’t tried it but you can try just having an AbsorbPointer widget inside of the header

**Comment by rupinderjeet** [comment]
Hello @Kavantix, thank you for the project.

I tried something like this:

```
SliverPinnedHeader(child: AbsorbPointer(child: _CommentsLabel()))
```

But, it didn't help me. I am able to scroll the page by using scroll gestures on pinned header.

**Comment by Kavantix** [comment]
Interesting it seems gestures break through an AbsorbPointer.
I did manage to get it working by wrapping the child of the `SliverPinnedHeader` in a `GestureDetector`:

```dart
child: GestureDetector(
  behavior: HitTestBehavior.opaque,
  onVerticalDragUpdate: (_) {},
  onHorizontalDragUpdate: (_) {},
  child: ...
)
```

This captures any horizontal and vertical drags on the header.

**Comment by rupinderjeet** [comment]
This fixes the issue. Do you think we can add this to documentation of `SliverPinnedHeader` as a tip?

Thank you.
