### ISSUE TITLE
Add MultiSliver.builder

### ISSUE THREAD

**Issue by allou-deyforyou** [Kavantix/sliver_tools#55]
Hey @Kavantix, @remonh87,
Please can you add MultiSliver.builder ?

**Comment by Kavantix** [comment]
@vodino It’s not that simple as I explained here: https://github.com/Kavantix/sliver_tools/issues/44#issuecomment-1096994549

If you have an idea for how the builder would work we can discuss it here.

Otherwise perhaps explaining your usecase could help

**Comment by Nedimko123** [comment]
Maybe just use a for loop although not memory efficient, just wanna say thanks @Kavantix for this awesome package, really needed the MultiSliver feature ;)
