### ISSUE TITLE
does it increase the performance like the default slivers?

### ISSUE THREAD

**Issue by balaji101010** [Kavantix/sliver_tools#64]
Instead of Listview inside Listview. we have used CustomScrollview -> SliverList , SliverList for better performance.

Does this library perform same as slivers or it affect the performance of the app
?

**Comment by Kavantix** [comment]
@balaji101010 can you elaborate a bit, I’m not entirely sure what your question is

**Comment by balaji101010** [comment]
Can I use this library and get same performance as default slivers? @Kavantix

**Comment by Kavantix** [comment]
It should, depending on how you use it of course
