### ISSUE TITLE
Error: A constant constructor can't call a non-constant super constructor.   

### ISSUE THREAD

**Issue by phuc-tranh-otsv** [Kavantix/sliver_tools#81]
When I run flutter build ios/android, I got the error:

`../../../../../.pub-cache/hosted/pub.dev/sliver_tools-0.2.11/lib/src/multi_sliver.dart:11:8: Error: A constant constructor can't call a non-constant super constructor.***) : super(key: key, children: children);../../../../../.pub-cache/hosted/pub.dev/sliver_tools-0.2.11/lib/src/sliver_stack.dart:19:8: Error: A constant constructor can't call a non-constant super constructor.***) : super(key: key, children: children);Target kernel_snapshot failed: ExceptionFAILURE: Build failed with an exception.`

Flutter version: 3.7.x

Solution: I use dependency_overrides: sliver_tools: 0.2.10 to fix it.

Please re-check & fix this error for next version. 

Thank you so much.

**Comment by phuc-tranh-otsv** [comment]
FYI: 
- sliver_tools: 0.2.10 MultiSliver isn't const class
- sliver_tools: 0.2.11 MultiSliver is const class

**Comment by Kavantix** [comment]
@phuc-tranh-otsv thanks for reporting this.
I've published 0.2.12 which again has it as non const
