### ISSUE TITLE
Flutter 3.13 Compatibility

### ISSUE THREAD

**Issue by robert-virkus** [Kavantix/sliver_tools#83]
Hi and thanks for the nice package.

On Flutter 3.13 I get the following compilation errors with version `sliver_tools: ^0.2.12`:

: Error: A value of type 'RenderObject?' can't be assigned to a variable of type 'AbstractNode?'.
sliver_stack.dart:282
- 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('/C:/flutter/packages/flutter/lib/src/rendering/object.dart').
object.dart:1
- 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('/C:/flutter/packages/flutter/lib/src/foundation/node.dart').
node.dart:1
      final AbstractNode? targetParent = renderObject.parent;
                                                      ^
: Error: The method 'markNeedsLayout' isn't defined for the class 'AbstractNode?'.
sliver_stack.dart:283
- 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('/C:/flutter/packages/flutter/lib/src/foundation/node.dart').
node.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'markNeedsLayout'.
      if (targetParent is RenderObject) targetParent.markNeedsLayout();

**Comment by Kavantix** [comment]
@robert-virkus This should be already fixed in 0.2.12, can you double check that the pubspec lock is also using 0.2.12?

**Comment by robert-virkus** [comment]
Thanks for your quick response, this was a `flutter pub upgrade` problem on my side.
