### ISSUE TITLE
[Enhancement Request] SliverAnimationSwitcher with transitionBuilder

### ISSUE THREAD

**Issue by sed1ka** [Kavantix/sliver_tools#88]
Hi! Thanks for the grateful plugin.
I have used `SliveAnimationSwitcher` but it currently only support the fade transition. It will be beautiful if `SliverAnimationSwitcher` supports `transitionBuilder` for custom transitions like the [AnimatedSwitcher](https://api.flutter.dev/flutter/widgets/AnimatedSwitcher-class.html).

**Comment by Kavantix** [comment]
Hi @sed1ka, `SliverAnimatedSwitcher` is simply a preconfigured normal `AnimatedSwitcher`
If you want to have a different transitionBuilder you can use the regular `AnimatedSwitcher` and set its `layoutBuilder` to `SliverAnimatedSwitcher.defaultLayoutBuilder` (see the docs of `SliverAnimatedSwitcher`)
