### ISSUE TITLE
Please provide the full example code from the gif

### ISSUE THREAD

**Issue by gidrokolbaska** [Kavantix/sliver_tools#90]
Hi!
Can you please provide the full code example which is showcased on the readme?
I can't figure out how to properly layout the widgets, so that the bottom radius is saved instead of being clipped:

https://github.com/Kavantix/sliver_tools/assets/54116985/df406152-7b74-4fbc-a5be-ca5c33154992

**Comment by Kavantix** [comment]
The link is documented here: https://github.com/Kavantix/sliver_tools/blob/master/example/example.md

**Comment by Kavantix** [comment]
But my guess would be that you have a background color on tour header that shouldn’t be there.

**Comment by gidrokolbaska** [comment]
> The link is documented here: https://github.com/Kavantix/sliver_tools/blob/master/example/example.md

Thanks for the example!
Now it works as I expected :)

https://github.com/Kavantix/sliver_tools/assets/54116985/6dfa6068-9438-4d2b-87ca-1be97b39919e


One more question though. Is it possible to keep the persistent header at top after it reaches its' min height and instead of moving it behind the appbar, fade it? Like in the ios weather app.
