### ISSUE TITLE
How to make it fit with custom ExpansionTile Widget ?

### ISSUE THREAD

**Issue by baptistemchl** [Kavantix/sliver_tools#92]
Hello guys, i created an expansionTile looks like widget,  and i want it to be my pinnedHeader. How can i make it work ?

Thanks for your replies

**Comment by Kavantix** [comment]
@baptistemchl please only open issues on github for bugs or feature requests.
Stackoverflow would be a good place to ask for help, but do provide a lot more information on what you have and want to achieve
